[build]
  command = "chmod +x netlify_build.sh && ./netlify_build.sh"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200